### MySQLi API

## Create Table

**mysqli_create.php**

***
```PHP
    <?php
// Configuración de la conexión a la base de datos
$servername = "localhost";
$username = "usuario";
$password = "contraseña";
$dbname = "testdb";

// Crear una conexión a la base de datos
$conn = new mysqli($servername, $username, $password, $dbname);

// Verificar la conexión
if ($conn->connect_error) {
    die("Error de conexión: " . $conn->connect_error);
}

// Consulta SQL para crear la tabla "employee"
$sql_create_table = 'CREATE TABLE employee( '.
                    'emp_id INT NOT NULL AUTO_INCREMENT, '.
                    'emp_name VARCHAR(20) NOT NULL,'.
                    'emp_address VARCHAR(20) NOT NULL, '. 
                    'emp_salary INT NOT NULL, '.
                    'PRIMARY KEY (emp_id))';

// Ejecutar la consulta para crear la tabla
if ($conn->query($sql_create_table) === TRUE) {
    echo "Tabla 'employee' creada exitosamente.<br>";

    // Consulta SQL para agregar un registro a la tabla
    $sql_insert_record = "INSERT INTO employee (emp_name, emp_address, emp_salary) VALUES ('Juan Perez', 'Calle Principal', 50000)";

    // Ejecutar la consulta para agregar el registro
    if ($conn->query($sql_insert_record) === TRUE) {
        echo "Registro agregado exitosamente.";
    } else {
        echo "Error al agregar el registro: " . $conn->error;
    }
} else {
    echo "Error al crear la tabla: " . $conn->error;
}

// Cerrar la conexión
$conn->close();
?>
    

```
***

## Select

**mysqli_select.php**

***
```PHP
    <?php
        $con=mysqli_connect("localhost", "root", "testdb");
        if(mysqli_connect_errno())
        {
            echo "Failed to connect to MySQL " . mysqli_connect_error();
            exit();
        }
        else
            echo "connection established successfully <br>"
        $sql="SELECT * FROM employee";
        $result=mysqli_query($con, $sql);
        $rowcount=mysqli_num_rows($result);
        for($i=0; $i <$rowcount; $i++){
            $row=mysqli_fetch_row($result);
            echo "emp_id -> " . $row[0] ."<br>"; 
            echo "emp_name -> " . $row[1] ."<br>"; 
            echo "emp_address -> " . $row[2] ."<br>"; 
            echo "emp_salary -> " . $row[3] ."<br>"; 
        }
        mysqli_free_result($result);
        mysqli_close();
    ?>
    

```
***

## Insert con peticion post

**insertar.html**

***
```HTML
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Empleado</title>
</head>
<body>
    <h2>Crear Empleado</h2>
    <form action="insertar_empleado.php" method="POST">
        <label for="emp_name">Nombre:</label>
        <input type="text" id="emp_name" name="emp_name"><br><br>
        
        <label for="emp_address">Dirección:</label>
        <input type="text" id="emp_address" name="emp_address"><br><br>
        
        <label for="emp_salary">Salario:</label>
        <input type="number" id="emp_salary" name="emp_salary"><br><br>
        
        <input type="submit" value="Crear Empleado">
    </form>
</body>
</html>

```
***

**insertar_empleado.php**

***
```PHP

<?php
// Configuración de la conexión a la base de datos
$servername = "localhost";
$username = "usuario";
$password = "contraseña";
$dbname = "testdb";

// Obtener los valores de la solicitud POST
$emp_name = $_POST['emp_name'];
$emp_address = $_POST['emp_address'];
$emp_salary = $_POST['emp_salary'];

// Crear una conexión a la base de datos
$conn = new mysqli($servername, $username, $password, $dbname);

// Verificar la conexión
if ($conn->connect_error) {
    die("Error de conexión: " . $conn->connect_error);
}

// Consulta SQL para agregar un registro a la tabla
$sql_insert_record = "INSERT INTO employee (emp_name, emp_address, emp_salary) VALUES ('$emp_name', '$emp_address', $emp_salary)";

// Ejecutar la consulta para agregar el registro
if ($conn->query($sql_insert_record) === TRUE) {
    echo "Registro agregado exitosamente.<br>";
    echo "<a href='index.html'>Volver al formulario</a>";
} else {
    echo "Error al agregar el registro: " . $conn->error;
}

// Cerrar la conexión
$conn->close();
?>
```
***

## Update con peticion post

**actualizar_empleado.html**

***
```HTML
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Empleado</title>
</head>
<body>
    <h2>Actualizar Empleado</h2>
    <form action="actualizar_empleado.php" method="POST">
        <label for="emp_id">ID del Empleado a Actualizar:</label>
        <input type="number" id="emp_id" name="emp_id" required><br><br>
        
        <label for="emp_name">Nuevo Nombre:</label>
        <input type="text" id="emp_name" name="emp_name"><br><br>
        
        <label for="emp_address">Nueva Dirección:</label>
        <input type="text" id="emp_address" name="emp_address"><br><br>
        
        <label for="emp_salary">Nuevo Salario:</label>
        <input type="number" id="emp_salary" name="emp_salary"><br><br>
        
        <input type="submit" value="Actualizar Empleado">
    </form>
</body>
</html>
```
***


**actualizar_empleado.php**

***
```PHP
<?php
// Configuración de la conexión a la base de datos
$servername = "localhost";
$username = "usuario";
$password = "contraseña";
$dbname = "testdb";

// Obtener los valores de la solicitud POST
$emp_id = $_POST['emp_id'];
$emp_name = $_POST['emp_name'];
$emp_address = $_POST['emp_address'];
$emp_salary = $_POST['emp_salary'];

// Crear una conexión a la base de datos
$conn = new mysqli($servername, $username, $password, $dbname);

// Verificar la conexión
if ($conn->connect_error) {
    die("Error de conexión: " . $conn->connect_error);
}

// Consulta SQL para actualizar el registro en la tabla
$sql_update_record = "UPDATE employee SET emp_name='$emp_name', emp_address='$emp_address', emp_salary=$emp_salary WHERE emp_id=$emp_id";

// Ejecutar la consulta para actualizar el registro
if ($conn->query($sql_update_record) === TRUE) {
    echo "Registro actualizado exitosamente.<br>";
    echo "<a href='actualizar_empleado.html'>Volver al formulario</a>";
} else {
    echo "Error al actualizar el registro: " . $conn->error;
}

// Cerrar la conexión
$conn->close();
?>
```
***

## Delete

**eliminar_empleado.html**

***
```HTML
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Empleado</title>
</head>
<body>
    <h2>Eliminar Empleado</h2>
    <form action="eliminar_empleado.php" method="POST">
        <label for="emp_id">ID del Empleado a Eliminar:</label>
        <input type="number" id="emp_id" name="emp_id" required><br><br>
        
        <input type="submit" value="Eliminar Empleado">
    </form>
</body>
</html>

```
***

**eliminar_empleado.php**

***
```PHP

<?php
// Configuración de la conexión a la base de datos
$servername = "localhost";
$username = "usuario";
$password = "contraseña";
$dbname = "testdb";

// Obtener el valor del ID del empleado a eliminar de la solicitud POST
$emp_id = $_POST['emp_id'];

// Crear una conexión a la base de datos
$conn = new mysqli($servername, $username, $password, $dbname);

// Verificar la conexión
if ($conn->connect_error) {
    die("Error de conexión: " . $conn->connect_error);
}

// Consulta SQL para eliminar el registro de la tabla
$sql_delete_record = "DELETE FROM employee WHERE emp_id=$emp_id";

// Ejecutar la consulta para eliminar el registro
if ($conn->query($sql_delete_record) === TRUE) {
    echo "Registro eliminado exitosamente.<br>";
    echo "<a href='eliminar_empleado.html'>Volver al formulario</a>";
} else {
    echo "Error al eliminar el registro: " . $conn->error;
}

// Cerrar la conexión
$conn->close();
?>

```
***

## Generar reporte PDF

Para generar un reporte en PDF de la información en la tabla "employee", puedes utilizar una librería PHP como TCPDF o FPDF. En este ejemplo, te mostraré cómo hacerlo utilizando TCPDF, que es una librería popular y fácil de usar para la generación de PDF en PHP.

Primero, asegúrate de haber descargado TCPDF desde su sitio web oficial o utilizando Composer si estás trabajando en un proyecto PHP que utiliza Composer. Luego, crea un archivo PHP llamado generar_reporte.php con el siguiente código:

**generar_reporte.php**


***
```PHP
<?php
// Incluir la librería TCPDF
require_once('tcpdf/tcpdf.php');

// Configuración de la conexión a la base de datos
$servername = "localhost";
$username = "usuario";
$password = "contraseña";
$dbname = "testdb";

// Crear una conexión a la base de datos
$conn = new mysqli($servername, $username, $password, $dbname);

// Verificar la conexión
if ($conn->connect_error) {
    die("Error de conexión: " . $conn->connect_error);
}

// Consulta SQL para obtener los datos de la tabla "employee"
$sql_select_data = "SELECT * FROM employee";
$result = $conn->query($sql_select_data);

// Crear un nuevo objeto TCPDF
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);

// Establecer el título del documento
$pdf->SetTitle('Reporte de Empleados');

// Agregar una página al documento
$pdf->AddPage();

// Configurar estilo y formato del texto
$pdf->SetFont('helvetica', '', 12);

// Encabezado del reporte
$html = '<h1>Reporte de Empleados</h1>';

// Construir la tabla con los datos de la consulta SQL
$html .= '<table border="1">';
$html .= '<tr><th>ID</th><th>Nombre</th><th>Dirección</th><th>Salario</th></tr>';

if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $html .= '<tr>';
        $html .= '<td>' . $row['emp_id'] . '</td>';
        $html .= '<td>' . $row['emp_name'] . '</td>';
        $html .= '<td>' . $row['emp_address'] . '</td>';
        $html .= '<td>' . $row['emp_salary'] . '</td>';
        $html .= '</tr>';
    }
}

$html .= '</table>';

// Agregar el contenido HTML al PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Cerrar la conexión
$conn->close();

// Salida del PDF al navegador
$pdf->Output('reporte_empleados.pdf', 'D');
?>

```
***